#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

if (! defined('SIGINT')) define('SIGINT', 2);
if (! defined('SIGTERM')) define('SIGTERM', 15);
if (! defined('SIGHUP')) define('SIGHUP', 1);
if (! defined('SIGTSTP')) define('SIGTSTP', 20);
if (! defined('SIGQUIT')) define('SIGQUIT', 3);
if (! defined('SIGUSR1')) define('SIGUSR1', 10);
if (! defined('SIGUSR2')) define('SIGUSR2', 12);

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
