{{-- Sign-off block, so a printed summary can be signed and filed. A
     provisional copy says it is not the one to sign. --}}
@php
    $signBox = 'break-inside-avoid rounded-lg border border-gray-200 px-4 py-3';
    $signLine = 'mt-8 border-t border-dashed border-gray-400 pt-1 text-[10px] uppercase tracking-wide text-gray-500';
    $consultantInCharge = $careTeam['consultant']?->name ?? $careTeam['consultantAtAdmission'];
@endphp

<section data-section="signoff" class="mb-5 {{ $sectionBox }}">
    <h3 class="{{ $sectionHeading }}">
        <span>Sign-off</span>
        @unless ($episode->isDischarged())
            <span class="font-semibold normal-case tracking-normal text-amber-700">
                Provisional &mdash; sign the final summary, after discharge
            </span>
        @endunless
    </h3>

    <div class="grid grid-cols-1 gap-3 p-3 sm:grid-cols-3 print:grid-cols-3">
        <div class="{{ $signBox }}">
            <p class="text-[10px] font-semibold uppercase tracking-wide text-gray-500">Summary generated by</p>
            <p class="mt-0.5 text-sm font-medium text-gray-900">{{ auth()->user()?->name ?? 'SmartWard' }}</p>
            <p class="text-xs text-gray-500">{{ ($generatedAt ?? now())->format('d M Y, H:i') }}</p>
            <p class="{{ $signLine }}">Signature</p>
        </div>

        <div class="{{ $signBox }}">
            <p class="text-[10px] font-semibold uppercase tracking-wide text-gray-500">Consultant in charge</p>
            <p class="mt-0.5 text-sm font-medium text-gray-900">{{ $consultantInCharge ?? '—' }}</p>
            <p class="text-xs text-gray-500">
                @if ($careTeam['consultant']?->registration_number)
                    Reg. {{ $careTeam['consultant']->registration_number }}
                @else
                    &nbsp;
                @endif
            </p>
            <p class="{{ $signLine }}">Signature &amp; date</p>
        </div>

        <div class="{{ $signBox }}">
            <p class="text-[10px] font-semibold uppercase tracking-wide text-gray-500">
                {{ $episode->isDischarged() ? 'Discharging nurse' : 'Nurse in charge' }}
            </p>
            <p class="mt-0.5 text-sm font-medium text-gray-900">
                {{ $episode->isDischarged() ? ($careTeam['dischargedBy']?->name ?? '—') : ($careTeam['nurse']?->name ?? '—') }}
            </p>
            <p class="text-xs text-gray-500">{{ $admission->ward?->ward_name }}</p>
            <p class="{{ $signLine }}">Signature &amp; date</p>
        </div>
    </div>
</section>
